language: node_js
node_js:
  - "6"
before_install:
  - "npm install -g web-component-tester"
  - "npm install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "wct --plugin local"
