language: java # This is npm project but selecting java for selenium testing
jdk: oraclejdk8
env: NODE_VERSION=6.10.0
before_install: nvm install $NODE_VERSION
install:
  - npm install
  - npm run lint
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: npm test
